language: node_js;

node_js: 
    -  "v12.18.3"

install:
- npm install

env:
  global:
     - CC_TEST_REPORTER_ID=2a1328adec361658c502fc9d5a2ffbaa4d86ae19e82d04da60352e3c0fc78ffa

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules
after_success:
  - npm run cover
  - npm run report-coverage
