ALTER TABLE users ALTER COLUMN gender DROP NOT NULL;
ALTER TABLE users ALTER COLUMN "home_address" DROP NOT NULL; 
ALTER TABLE users ALTER COLUMN "state" DROP NOT NULL; 
ALTER TABLE users ALTER COLUMN "lga" DROP NOT NULL; 